@GifCampAPI_HostAddress = http://localhost:5255

### Login
POST {{GifCampAPI_HostAddress}}/login
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "picture": "https://example.com/picture.jpg",
  "method": "google"
}

###

### Category Add
POST {{GifCampAPI_HostAddress}}/category-add
Content-Type: application/json

{
  "userId": 1,
  "name": "My Category"
}

###

### Category All
POST {{GifCampAPI_HostAddress}}/category-all
Content-Type: application/json

{
  "userId": 1
}

###
