@GifCampAPI_HostAddress = http://localhost:5255

### Login
POST {{GifCampAPI_HostAddress}}/login
Content-Type: application/json

{
  "name": "John Doe",
  "email": "john.doe@example.com",
  "picture": "https://example.com/picture.jpg",
  "method": "google"
}

###

### Category Add
POST {{GifCampAPI_HostAddress}}/category-add
Content-Type: application/json

{
  "userId": 1,
  "name": "My Category"
}

###

### Category All
POST {{GifCampAPI_HostAddress}}/category-all
Content-Type: application/json

{
  "userId": 1
}

###

### Category Delete
POST {{GifCampAPI_HostAddress}}/category-delete
Content-Type: application/json

{
  "userId": 1,
  "categoryId": 1
}

###

### Image Add Link
POST {{GifCampAPI_HostAddress}}/images-add-link
Content-Type: application/json

{
  "userId": 1,
  "categoryId": 1,
  "imageUrl": "https://example.com/image.jpg"
}

###

### Image Add Blob
POST {{GifCampAPI_HostAddress}}/images-add-blob
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="userId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="categoryId"

1
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="image.jpg"
Content-Type: image/jpeg

< ./path/to/image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

### Image Get
POST {{GifCampAPI_HostAddress}}/images-get
Content-Type: application/json

{
  "userId": 1,
  "categoryId": -1
}

###

### Image Delete
POST {{GifCampAPI_HostAddress}}/images-delete
Content-Type: application/json

{
  "userId": 1,
  "imageId": 1
}

###
